---
name: 'kasterpalu.ee'
services:
  web:
    container_name: 'kasterpalu-web'
    build:
      context: .
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - SESH_SECRET
      - ALTCHA_HMAC
      - UPSTASH_REDIS_URL
      - UPSTASH_REDIS_TOKEN
    restart: unless-stopped
    ports:
      - 9000:3000
